#!/usr/bin/env python3
# -*- coding: latin-1 -*-

import os

def detectFlag(s, key):
    if s.find(key) == -1:
        return 0
    else:
        return 1
    
def openFile(file):
    try:
        fd_ssh = open(file,"r")
        return fd_ssh;
    except IOError:
        print ("Could not open file! please verify file configuration")
        return None;

def ClearTab(lines):
    for i in range(0, len(lines)):
        lines[i] = lines[i].rstrip()
    return (lines)
        
if __name__ == '__main__':
    print ("Security Project")
    ssh_log = "/var/log/auth.log"
    print ("[%s]" % ssh_log)
    size = os.stat(ssh_log).st_size
    print (size)
    while True:
        new_size = os.stat(ssh_log).st_size
        if new_size != size:
            print ("fichier modifier")
            fd = openFile(ssh_log)
            if fd is not None:
                print ("le fichier est ouvert")
                print (size)
                fd.seek(size, 0)
                lines = fd.readlines()
                lines = ClearTab(lines)
                #line = line.rstrip("\n")              
                print (lines)
            size = new_size
